#!/bin/bash

# Navigate to the directory containing the virtual environment and project
cd emarkt

# Create the virtual environment
python -m venv venv-emarkt

# Activate the virtual environment
source venv-emarkt/bin/activate

# Upgrade pip and install necessary packages
pip install --upgrade pip
pip install django
pip install Pillow

# Verify Django installation
django-admin --version

# Navigate to the Django project directory
cd ../emarkt

# Perform migrations, if necessary
python manage.py makemigrations
python manage.py migrate


# Run the Django development server
python manage.py runserver

